services:

# ########################################################################## #
#                                 JDOWNLOADER                                #
# ########################################################################## #

  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    environment:
      - PUID=3000
      - PGID=3000
    ports:
      - "5800:5800"
    volumes:
      - "./jdownloader:/config:rw"
      - "smb_downloads:/output:rw"
    restart: unless-stopped
  

# ########################################################################## #
#                                  OVERSEER                                  #
# ########################################################################## #

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/Documents/Projects/Media_Stack/media_stack/overseer/configs:/config
    ports:
      - 5055:5055
    restart: unless-stopped

# ########################################################################## #
#                                  JELLYSEER                                 #
# ########################################################################## #
#  jellyseerr:
#    image: fallenbagel/jellyseerr:latest
#    container_name: jellyseerr
#    environment:
#      - LOG_LEVEL=debug
#      - TZ=Etc/UTC
#      - PORT=5055 #optional
#    ports:
#      - 5055:5055
#    volumes:
#      - ./jellyseerr/data:/app/config
#    restart: unless-stopped
# ########################################################################## #
#                                   CALIBRE                                  #
# ########################################################################## #
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
     # - PASSWORD= #optional
     # - CLI_ARGS= #optional
    volumes:
      - ./calibre/data:/config
      - smb_books:/books #optional
      # - smb_calibre:/books_staging #optional
    ports:
      - 9090:8080
      - 9191:8181
      - 9091:8081
    restart: unless-stopped
# ########################################################################## #
#                                  JELLYFIN                                  #
# ########################################################################## #
#   jellyfin:
#     image: lscr.io/linuxserver/jellyfin:latest
#     container_name: jellyfin
#     environment:
#       - PUID=3000
#       - PGID=3000
#       - TZ=Etc/UTC
#  #     - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
#     volumes:
#       - ./jellyfin/data:/config
#       - smb_anime:/anime
#       - smb_tvseries:/tv
#       - smb_movies:/movies
#     ports:
#       - 8096:8096
# #      - 8920:8920 #optional
# #      - 7359:7359/udp #optional
#  #     - 1900:1900/udp #optional
#     restart: unless-stopped

# ########################################################################## #
#                                    PLEX                                    #
# ########################################################################## #
  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   container_name: plex
  #   network_mode: host
  #   environment:
  #     - PUID=3000
  #     - PGID=3000
  #     - TZ=Etc/UTC
  #     - VERSION=docker
  # #    - PLEX_CLAIM= #optional
  #   volumes:
  #     - ./plex/data:/config
  #     - smb_anime:/anime
  #     - smb_tvseries:/tv
  #     - smb_movies:/movies
  #   restart: unless-stopped


# ########################################################################## #
#                                   SABNZB                                   #
# ########################################################################## #
#  sabnzbd:
#    image: lscr.io/linuxserver/sabnzbd:latest
#    container_name: sabnzbd
#    environment:
#      - PUID=3000
#      - PGID=3000
#      - TZ=Etc/UTC
#    volumes:
#      - ./sabnzbd/config:/config
#      - smb_downloads:/downloads #optional
#      - smb_incomplete_downloads:/incomplete-downloads #optional
#    ports:
#      - 8081:8080
#    restart: unless-stopped
# ########################################################################## #
#                                 QBITTORRENT                                #
# ########################################################################## #
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config # path to the folder on your host machine where you want to store the Radarr configuration files
      - smb_downloads:/downloads # path for downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
# ########################################################################## #
#                                   HOMARR                                   #
# ########################################################################## #
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
    ports:
      - '7575:7575'
# ########################################################################## #
#                                   BAZARR                                   #
# ########################################################################## #
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - /path/to/bazarr/config:/config
      - smb_tvseries:/tv #optional
      - smb_anime:/anime #optional
      - smb_movies:/movies #optional
    ports:
      - 6767:6767
    restart: unless-stopped
# ########################################################################## #
#                                   SONAAR                                   #
# ########################################################################## #
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./sonarr/data:/config
      - smb_tvseries:/tv #optional
      - smb_anime_series:/anime/series #optional
      - smb_downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
# ########################################################################## #
#                                   RADARR                                   #
# ########################################################################## #
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./radarr/data:/config
      - smb_movies:/movies #optional
      - smb_anime_movies:/anime/movies #optional
      - smb_downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
# ########################################################################## #
#                                   READARR                                  #
# ########################################################################## #
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./readarr/data:/config
      - smb_books:/books #optional
      - smb_downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
# ########################################################################## #
#                                  PROWLARR                                  #
# ########################################################################## #
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr/data:/config
      - smb_downloads:/downloads # optional
    ports:
      - 9696:9696
    restart: unless-stopped
# ########################################################################## #
#                                    TDARR                                   #
# ########################################################################## #
  # tdarr:
  #   container_name: tdarr
  #   # image: ghcr.io/haveagitgat/tdarr:latest
  #   image: ghcr.io/haveagitgat/tdarr_node:latest
  #   restart: unless-stopped
  #   network_mode: bridge
  #   # ports:
  #   #   - 8265:8265 # webUI port
  #   #   - 8266:8266 # server port
  #   environment:
  #     - PUID=3000
  #     - PGID=3000
  #     - auth=True
  #     - TZ=Etc/UTC
  #     # - webUIPort=8265
  #     # - serverIP=0.0.0.0
  #     - serverPort=8266
  #     - serverIP=192.168.0.115
  #     # - internalNode=true
  #     - inContainer=true
  #     - nodeName=ExternalNode2
  #   volumes:
  #     - ./tdarr/server:/app/server
  #     - ./tdarr/logs:/app/logs
  #     - smb_tdarr_configs:/app/configs
  #     - smb_tdarr_cache:/temp
  #     - smb_movies:/media/movies
  #     - smb_tvseries:/media/tvseries
  #     - smb_anime:/media/anime
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2' # Limit the container to use 2 CPU cores

volumes:
  smb_share:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share"  
  smb_books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/books"  
  smb_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/downloads" 
  smb_incomplete_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/incomplete-downloads"
  smb_tdarr_cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/tdarr/transcode_cache"
  smb_tdarr_configs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/tdarr/configs"
  smb_movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/movies"
  smb_tvseries:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/tvseries"
  smb_anime:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/anime"
  smb_anime_movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/anime/movies"
  smb_anime_series:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/anime/series"
  smb_calibre:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.115,rw,nolock,hard,nfsvers=4
      device: ":/share/calibre/tmp"
