version: "3.7"

services:
  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PUID=1000 #change this to the correct one
      - PGID=1000 #change this to the correct one
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /Users/andrew/arr/sonarr/config:/config # path to the folder on your host machine where you want to store the Radarr configuration files
      - /Users/andrew/arr/media/series:/series # path for movies
      - /Users/andrew/arr/media/downloads:/downloads # path for downloads