version: "3.7"

services:
  sonarr:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: always
    environment:
      - PUID=1000 #change this to the correct one
      - PGID=1000 #change this to the correct one
      - UMASK=002
      - WEBUI_PORT=8080
      - TZ=Etc/UTC
    volumes:
      - /Users/andrew/arr/qbittorrent:/config # path to the folder on your host machine where you want to store the Radarr configuration files
      - /Users/andrew/arr/media/downloads:/downloads # path for downloads