version: "3.7"

services:
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PUID=1000 #change this to the correct one
      - PGID=1000 #change this to the correct one
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /Users/andrew/arr/radarr/config:/config # path to the folder on your host machine where you want to store the Radarr configuration files
      - /Users/andrew/arr/media/movies:/movies # path for movies
      - /Users/andrew/arr/media/downloads:/downloads # path for downloads