version: "3.7"

services:
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /Users/andrew/Documents/Projects/Personal/MEDIA_STACK/media_stack/docker_images/radarr/config # path to the folder on your host machine where you want to store the Radarr configuration files
